baseURL = "https://mlcore-engine.github.io/"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title = "高新 | AI平台开发工程师"
theme = "techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

# 启用网站地图
enableRobotsTXT = true
enableGitInfo = true  # 使用Git信息作为lastmod

[params]
    # 基本信息
    description = "AI平台开发工程师，专注于AI平台工程和Kubernetes云原生技术。拥有AI平台开发、GPU资源优化和AI服务部署经验"
    keywords = "AI, 机器学习, golang, kubernetes, 技术博客"
    author = "高新"
    
    # 文档仓库
    github_repository = "https://github.com/mlcore-engine/mlcore-engine"
    
    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"
    
    # Theme settings section
    # Theme color
    custom_font_color = "#ffffff"  # 白色字体
    custom_background_color = "#1a365d"  # 深蓝色背景

    # Documentation Menu section
    # Menu style settings
    dateformat = "2006-01-02" # 使用中文习惯的日期格式

    # Open Graph settings
    title = "高新 | AI平台开发工程师" 
    images = ["home/me.png"] # Open graph images

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
    ]

# Sitemap配置
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Markup configure section
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe = true
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = false

[build]
  writeStats = true